# Generated by Django 5.0.6 on 2024-07-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='conatact/%Y/%m/%d'),
        ),
    ]
