# Generated by Django 5.0.6 on 2024-07-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='civility',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contacts/%Y/%m/%d'),
        ),
    ]
